In [1]:
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import TimeoutException, NoSuchElementException
from datetime import date

In [2]:
df = pd.read_csv('PC_Gamer.csv', sep=';')
df.head()

          Item                          Descricao    Preco        Data
0          CPU                 AMD Ryzen 5 5600GT  1032.93  2026-06-04
1  Motherboard                   Chronos B550M-CR   647.05  2026-06-04
2          RAM  2x Hyper X Fury DDR4 8GB 3200 MHz   548.21  2026-06-04
3     Gabinete                    C3tech Aquarius   299.83  2026-06-04
4        Mouse          Attack Shark Wireless X11   114.29  2026-06-04

## Processador

In [3]:
driver = webdriver.Chrome()
driver.get('https://www.amazon.com.br/Processador-AMD-Ryzen-5600GT-Threads/dp/B0CQ4DTJYX/ref=asc_df_B0CQ4DTJYX?mcid=ee61770518f834679b2c75152745b69b&tag=googleshopp00-20&linkCode=df0&hvadid=709884378235&hvpos=&hvnetw=g&hvrand=14881669649454203673&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9101448&hvtargid=pla-2280624564623&psc=1&language=pt_BR&gad_source=1')

driver.implicitly_wait(5)

try:
    # Tenta encontrar o elemento com o XPath específico
    botao_continuar = driver.find_element(By.XPATH, "/html/body/div/div[1]/div[3]/div/div/form/div/div/span")
    
    # Se encontrou, clica
    botao_continuar.click()
    print("Botão encontrado e clicado com sucesso!")
    
    # Aguarda a navegação após o clique
    WebDriverWait(driver, 5).until(EC.staleness_of(botao_continuar))
    
except NoSuchElementException:
    # Se não encontrou, apenas continua
    print("Botão NÃO encontrado. Continuando execução...")

Botão NÃO encontrado. Continuando execução...

In [5]:
best_offer = driver.find_element(By.ID, 'best-offer-string-cc').get_property('innerHTML')

price_cpu_ptbr = best_offer.split(' ')[1].split(';')[1]
cpu_price = price_cpu_ptbr.replace('.', '').replace(',', '.')
cpu_price = float(cpu_price)
cpu_price

1000.15

In [ ]:
item = 'CPU'
descricao = 'AMD Ryzen 5 5600GT'
data = date.today()

new_data = pd.DataFrame([{
    'Item': item,
    'Descricao': descricao,
    'Preco': cpu_price,
    'Data': data
}])

df = pd.concat([df, new_data], ignore_index=True)
df.tail(10)

           Item                          Descricao    Preco        Data
0           CPU                 AMD Ryzen 5 5600GT  1032.93  2026-06-04
1   Motherboard                   Chronos B550M-CR   647.05  2026-06-04
2           RAM  2x Hyper X Fury DDR4 8GB 3200 MHz   548.21  2026-06-04
3      Gabinete                    C3tech Aquarius   299.83  2026-06-04
4         Mouse          Attack Shark Wireless X11   114.29  2026-06-04
5       Headset                  BINNUNE Bluetooth    93.11  2026-06-04
6      Soundbar                            NIYE V8    99.20  2026-06-04
7           CPU                 AMD Ryzen 5 5600GT  1032.93  2026-06-09
8   Motherboard                   Chronos B550M-CR   647.05  2026-06-09
9           RAM  2x Hyper X Fury DDR4 8GB 3200 MHz   567.91  2026-06-09
10     Gabinete                    C3tech Aquarius   299.83  2026-06-09
11        Mouse          Attack Shark Wireless X11   116.30  2026-06-09
12      Headset                  BINNUNE Bluetooth    99.76  2026-06-09
13     Soundbar                            NIYE V8   100.92  2026-06-09
14          CPU                 AMD Ryzen 5 5600GT  1031.76  2026-06-15
15  Motherboard                   Chronos B550M-CR   647.05  2026-06-15
16          RAM  2x Hyper X Fury DDR4 8GB 3200 MHz   553.70  2026-06-15
17     Gabinete                    C3tech Aquarius   299.83  2026-06-15
18        Mouse          Attack Shark Wireless X11   135.81  2026-06-15
19      Headset                  BINNUNE Bluetooth    99.58  2026-06-15
20     Soundbar                            NIYE V8    98.32  2026-06-15
21          CPU                 AMD Ryzen 5 5600GT  1031.76  2026-06-21
22  Motherboard                   Chronos B550M-CR   647.05  2026-06-21
23          RAM  2x Hyper X Fury DDR4 8GB 3200 MHz   581.99  2026-06-21
24     Gabinete                    C3tech Aquarius   299.83  2026-06-21
25        Mouse          Attack Shark Wireless X11   154.99  2026-06-21
26      Headset                  BINNUNE Bluetooth   105.61  2026-06-21
27     Soundbar                            NIYE V8   117.99  2026-06-21
28          CPU                 AMD Ryzen 5 5600GT  1000.15  2026-06-28

## Motherboard

In [32]:
driver.get('https://www.terabyteshop.com.br/produto/18646/placa-mae-msi-b550m-a-pro-chipset-b550-amd-am4-matx-ddr4?gad_source=1&gad_campaignid=16136003025&gclid=CjwKCAjw-dfOBhAjEiwAq0RwIz8B9H8t5nWpALxwlzeNSRzDe_0N0SyEK5sfVcw5-6LGCgzhKTTASBoCiYIQAvD_BwE')

In [8]:
mboard_ptbr = driver.find_element(By.ID, 'valParc').get_property('innerText')
mboard_price = mboard_ptbr.split(' ')[1].replace(',', '.')
mboard_price = float(mboard_price)
mboard_price

647.05

In [9]:
item = 'Motherboard'
descricao = 'Chronos B550M-CR'
data = date.today()

new_data = pd.DataFrame([{
    'Item': item,
    'Descricao': descricao,
    'Preco': mboard_price,
    'Data': data
}])

df = pd.concat([df, new_data], ignore_index=True)
df.tail(10)

           Item                          Descricao    Preco        Data
20     Soundbar                            NIYE V8    98.32  2026-06-15
21          CPU                 AMD Ryzen 5 5600GT  1031.76  2026-06-21
22  Motherboard                   Chronos B550M-CR   647.05  2026-06-21
23          RAM  2x Hyper X Fury DDR4 8GB 3200 MHz   581.99  2026-06-21
24     Gabinete                    C3tech Aquarius   299.83  2026-06-21
25        Mouse          Attack Shark Wireless X11   154.99  2026-06-21
26      Headset                  BINNUNE Bluetooth   105.61  2026-06-21
27     Soundbar                            NIYE V8   117.99  2026-06-21
28          CPU                 AMD Ryzen 5 5600GT  1000.15  2026-06-28
29  Motherboard                   Chronos B550M-CR   647.05  2026-06-28

## SSD

In [10]:
driver.get('https://pt.aliexpress.com/item/1005006783107881.html?sourceType=620&channel=coin&improveDiscount=Y&BuyNow=true&utm=iskandarsouzo_sophie&aff_fcid=776b93166200483383f7ee2b8c7a626b-1783267233933-06465-_c3nNHgTr&tt=API&aff_fsk=_c3nNHgTr&afSmartRedirect=y&dp=gx-br-aliexpress-aliexpress-cos&aff_fcid=158f311f0235481b9d6724a876e86c26-1783274078397-07732-_c3IGhl7b&tt=CPS_NORMAL&aff_fsk=_c3IGhl7b&aff_platform=portals-tool&sk=_c3IGhl7b&aff_trace_key=158f311f0235481b9d6724a876e86c26-1783274078397-07732-_c3IGhl7b&terminal_id=e7a44edf1bc34d368a13eb65be5c194e&afSmartRedirect=y')

In [13]:
button = driver.find_element(By.XPATH, "//div[@title='1TB']")
button.click()

ssd_price_ptbr = driver.find_element(By.XPATH, "//div[@class='price-default--currentWrap--A_MNgCG']").get_property('innerText')
ssd_price = ssd_price_ptbr.split('$')[1].replace(',', '.')
ssd_price = float(ssd_price)
ssd_price

924.29

In [ ]:
item = 'SSD'
descricao = 'Movespeed ssd nvme 1TB'
data = date.today()

new_data = pd.DataFrame([{
    'Item': item,
    'Descricao': descricao,
    'Preco': ram_price,
    'Data': data
}])

df = pd.concat([df, new_data], ignore_index=True)
df.tail(10)

## RAM

In [4]:

driver.get('https://pt.aliexpress.com/item/1005012323512000.html?pdp_ext_f=%7B"sku_id"%3A"12000058084377368"%7D&sourceType=1&spm=a2g0o.wish-manage-home.0.0&gatewayAdapt=glo2bra')

In [ ]:
#button = driver.find_element(By.XPATH, "//div[contains(@title, '2PCS 8GB 3200')]")
#button.click()

ram_price_ptbr = driver.find_element(By.XPATH, "//div[@class='price-default--currentWrap--A_MNgCG']").get_property('innerText')
ram_price = ram_price_ptbr.split('$')[1].replace(',', '.')
ram_price = float(ram_price)
ram_price

257.16

In [ ]:
item = 'RAM'
descricao = '1x JUHOR DDR4 8GB 3200MHz CL16'
data = date.today()

new_data = pd.DataFrame([{
    'Item': item,
    'Descricao': descricao,
    'Preco': ram_price,
    'Data': data
}])

df = pd.concat([df, new_data], ignore_index=True)
df.tail(10)

           Item                          Descricao    Preco        Data
21          CPU                 AMD Ryzen 5 5600GT  1031.76  2026-06-21
22  Motherboard                   Chronos B550M-CR   647.05  2026-06-21
23          RAM  2x Hyper X Fury DDR4 8GB 3200 MHz   581.99  2026-06-21
24     Gabinete                    C3tech Aquarius   299.83  2026-06-21
25        Mouse          Attack Shark Wireless X11   154.99  2026-06-21
26      Headset                  BINNUNE Bluetooth   105.61  2026-06-21
27     Soundbar                            NIYE V8   117.99  2026-06-21
28          CPU                 AMD Ryzen 5 5600GT  1000.15  2026-06-28
29  Motherboard                   Chronos B550M-CR   647.05  2026-06-28
30          RAM  2x Hyper X Fury DDR4 8GB 3200 MHz   526.99  2026-06-28

## Gabinete

In [34]:
driver.get('https://www.kabum.com.br/produto/887046/gabinete-gaming-c3tech-aquarius-com-vidro-temperado-sem-fonte-mt-g860bk-')

In [35]:
button = driver.find_element(By.ID, "adopt-accept-all-button")
button.click()

gabinete_ptbr = driver.find_element(By.XPATH, "(//div[@class='w-full']/span/b)").get_property('innerText')
gabinete_price = gabinete_ptbr.split('\xa0')[1].replace(',', '.')
gabinete_price = float(gabinete_price)
gabinete_price

289.72

In [36]:
item = 'Gabinete'
descricao = 'C3tech Aquarius'
data = date.today()

new_data = pd.DataFrame([{
    'Item': item,
    'Descricao': descricao,
    'Preco': gabinete_price,
    'Data': data
}])

df = pd.concat([df, new_data], ignore_index=True)
df.tail(10)

           Item                          Descricao    Preco        Data
22  Motherboard                   Chronos B550M-CR   647.05  2026-06-21
23          RAM  2x Hyper X Fury DDR4 8GB 3200 MHz   581.99  2026-06-21
24     Gabinete                    C3tech Aquarius   299.83  2026-06-21
25        Mouse          Attack Shark Wireless X11   154.99  2026-06-21
26      Headset                  BINNUNE Bluetooth   105.61  2026-06-21
27     Soundbar                            NIYE V8   117.99  2026-06-21
28          CPU                 AMD Ryzen 5 5600GT  1000.15  2026-06-28
29  Motherboard                   Chronos B550M-CR   647.05  2026-06-28
30          RAM  2x Hyper X Fury DDR4 8GB 3200 MHz   526.99  2026-06-28
31     Gabinete                    C3tech Aquarius   289.72  2026-06-28

## Mouse

In [17]:
driver.get('https://pt.aliexpress.com/item/1005012371400759.html?spm=a2g0o.productlist.main.23.459c25f81bcfCL&algo_pvid=fe26c5bb-67a9-42a2-8835-77951b1c0678&algo_exp_id=fe26c5bb-67a9-42a2-8835-77951b1c0678-20&pdp_ext_f=%7B"order"%3A"23"%2C"eval"%3A"1"%2C"fromPage"%3A"search"%7D&pdp_npi=6%40dis%21BRL%21336.34%21147.99%21%21%21407.73%21179.40%21%402101f70717832764055654429e72c1%2112000058191763437%21sea%21BR%217714416806%21X%211%210%21n_tag%3A-29911%3Bd%3A137eff22%3Bm03_new_user%3A-29895&curPageLogUid=Lq0Biyq3hzZX&utparam-url=scene%3Asearch%7Cquery_from%3A%7Cx_object_id%3A1005012371400759%7C_p_origin_prod%3A')

In [15]:
#button = driver.find_element(By.XPATH, "(//div[@class='sku-item--image--jMUnnGA'])[3]")
#button.click()

mouse_ptbr = driver.find_element(By.XPATH, "(//div[@class='price-default--currentWrap--A_MNgCG'])").get_property('innerText')
mouse_price = mouse_ptbr.split('$')[1].replace(',', '.')
mouse_price = float(mouse_price)
mouse_price

127.97

In [42]:
item = 'Mouse'
descricao = 'Attack Shark Wireless X11'
data = date.today()

new_data = pd.DataFrame([{
    'Item': item,
    'Descricao': descricao,
    'Preco': mouse_price,
    'Data': data
}])

df = pd.concat([df, new_data], ignore_index=True)
df.tail(10)

           Item                          Descricao    Preco        Data
23          RAM  2x Hyper X Fury DDR4 8GB 3200 MHz   581.99  2026-06-21
24     Gabinete                    C3tech Aquarius   299.83  2026-06-21
25        Mouse          Attack Shark Wireless X11   154.99  2026-06-21
26      Headset                  BINNUNE Bluetooth   105.61  2026-06-21
27     Soundbar                            NIYE V8   117.99  2026-06-21
28          CPU                 AMD Ryzen 5 5600GT  1000.15  2026-06-28
29  Motherboard                   Chronos B550M-CR   647.05  2026-06-28
30          RAM  2x Hyper X Fury DDR4 8GB 3200 MHz   526.99  2026-06-28
31     Gabinete                    C3tech Aquarius   289.72  2026-06-28
32        Mouse          Attack Shark Wireless X11   136.13  2026-06-28

## Headset

In [16]:
driver.get('https://pt.aliexpress.com/item/1005009495386384.html?aff_fcid=24cb7ac286da4a1dac72bd6b45a01629-1779218687223-01059-_c3gITj9D&tt=CPS_NORMAL&aff_fsk=_c3gITj9D&aff_platform=shareComponent-detail&sk=_c3gITj9D&aff_trace_key=24cb7ac286da4a1dac72bd6b45a01629-1779218687223-01059-_c3gITj9D&terminal_id=d874b61df0ea490bb40119dc36685fe8&afSmartRedirect=y')

In [44]:
button = driver.find_element(By.XPATH, '/html/body/div[3]/div/div[1]/div/div[1]/div[1]/div[2]/div[8]/div/div/div[2]/div/div/div/div/div[5]')
button.click()

headset_ptbr = driver.find_element(By.XPATH, '/html/body/div[3]/div/div[1]/div/div[1]/div[1]/div[2]/div[4]/div/div[2]/div[1]/div[1]/span').get_property('innerText')
headset_price = headset_ptbr.split('$')[1].replace(',', '.')
headset_price = float(headset_price)
headset_price

120.81

In [45]:
item = 'Headset'
descricao = 'BINNUNE Bluetooth'
data = date.today()

new_data = pd.DataFrame([{
    'Item': item,
    'Descricao': descricao,
    'Preco': headset_price,
    'Data': data
}])

df = pd.concat([df, new_data], ignore_index=True)
df.tail(10)

           Item                          Descricao    Preco        Data
24     Gabinete                    C3tech Aquarius   299.83  2026-06-21
25        Mouse          Attack Shark Wireless X11   154.99  2026-06-21
26      Headset                  BINNUNE Bluetooth   105.61  2026-06-21
27     Soundbar                            NIYE V8   117.99  2026-06-21
28          CPU                 AMD Ryzen 5 5600GT  1000.15  2026-06-28
29  Motherboard                   Chronos B550M-CR   647.05  2026-06-28
30          RAM  2x Hyper X Fury DDR4 8GB 3200 MHz   526.99  2026-06-28
31     Gabinete                    C3tech Aquarius   289.72  2026-06-28
32        Mouse          Attack Shark Wireless X11   136.13  2026-06-28
33      Headset                  BINNUNE Bluetooth   120.81  2026-06-28

## Soundbar

In [46]:
driver.get('https://pt.aliexpress.com/item/1005006436035998.html?spm=a2g0o.productlist.main.2.26c7y0DSy0DSur&algo_pvid=a6a82e3c-ebe8-41ee-9da0-1fe9c6c92b4a&algo_exp_id=a6a82e3c-ebe8-41ee-9da0-1fe9c6c92b4a-1&pdp_ext_f=%7B"order"%3A"4969"%2C"spu_best_type"%3A"price"%2C"eval"%3A"1"%2C"fromPage"%3A"search"%7D&pdp_npi=6%40dis%21BRL%21229.12%21100.55%21%21%21287.08%21125.98%21%402103212b17798072772552193e62f7%2112000037173402947%21sea%21BR%210%21ABX%211%210%21n_tag%3A-29910%3Bd%3Aeaf596e%3Bm03_new_user%3A-29895%3BpisId%3A5000000207258923&curPageLogUid=jr5V9vRJV1Bl&utparam-url=scene%3Asearch%7Cquery_from%3A%7Cx_object_id%3A1005006436035998%7C_p_origin_prod%3A')

In [49]:
soundbar_ptbr = driver.find_element(By.XPATH, "(//div[@class='price-default--currentWrap--A_MNgCG'])").get_property('innerText')
soundbar_price = soundbar_ptbr.split('$')[1].replace(',', '.')
soundbar_price = float(soundbar_price)
soundbar_price

104.11

In [50]:
item = 'Soundbar'
descricao = 'NIYE V8'
data = date.today()

new_data = pd.DataFrame([{
    'Item': item,
    'Descricao': descricao,
    'Preco': soundbar_price,
    'Data': data
}])

df = pd.concat([df, new_data], ignore_index=True)
df.tail(10)

           Item                          Descricao    Preco        Data
25        Mouse          Attack Shark Wireless X11   154.99  2026-06-21
26      Headset                  BINNUNE Bluetooth   105.61  2026-06-21
27     Soundbar                            NIYE V8   117.99  2026-06-21
28          CPU                 AMD Ryzen 5 5600GT  1000.15  2026-06-28
29  Motherboard                   Chronos B550M-CR   647.05  2026-06-28
30          RAM  2x Hyper X Fury DDR4 8GB 3200 MHz   526.99  2026-06-28
31     Gabinete                    C3tech Aquarius   289.72  2026-06-28
32        Mouse          Attack Shark Wireless X11   136.13  2026-06-28
33      Headset                  BINNUNE Bluetooth   120.81  2026-06-28
34     Soundbar                            NIYE V8   104.11  2026-06-28

## Saving DataFrame

In [51]:
df.to_csv('PC_Gamer.csv', sep=';', index=None)

driver.close()