In [96]:
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import TimeoutException, NoSuchElementException
from datetime import date

In [97]:
df = pd.DataFrame(columns=['Item', 'Descricao', 'Preco', 'Data'])
df

Empty DataFrame
Columns: [Item, Descricao, Preco, Data]
Index: []

## Processador

In [99]:
driver = webdriver.Chrome()
driver.get('https://www.amazon.com.br/Processador-AMD-Ryzen-5600GT-Threads/dp/B0CQ4DTJYX/ref=asc_df_B0CQ4DTJYX?mcid=ee61770518f834679b2c75152745b69b&tag=googleshopp00-20&linkCode=df0&hvadid=709884378235&hvpos=&hvnetw=g&hvrand=14881669649454203673&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9101448&hvtargid=pla-2280624564623&psc=1&language=pt_BR&gad_source=1')

driver.implicitly_wait(5)

try:
    # Tenta encontrar o elemento com o XPath específico
    botao_continuar = driver.find_element(By.XPATH, "/html/body/div/div[1]/div[3]/div/div/form/div/div/span")
    
    # Se encontrou, clica
    botao_continuar.click()
    print("Botão encontrado e clicado com sucesso!")
    
    # Aguarda a navegação após o clique
    WebDriverWait(driver, 5).until(EC.staleness_of(botao_continuar))
    
except NoSuchElementException:
    # Se não encontrou, apenas continua
    print("Botão NÃO encontrado. Continuando execução...")

Botão encontrado e clicado com sucesso!

In [100]:
best_offer = driver.find_element(By.ID, 'best-offer-string-cc').get_property('innerHTML')
best_offer

'ou R$&nbsp;1.032,93 em até 10x de R$&nbsp;103,32 sem juros'

In [12]:
type(best_offer)

str

In [101]:
price_cpu_ptbr = best_offer.split(' ')[1].split(';')[1]
cpu_price = price_cpu_ptbr.replace('.', '').replace(',', '.')
cpu_price = float(cpu_price)
cpu_price

1032.93

In [102]:
item = 'CPU'
descricao = 'AMD Ryzen 5 5600GT'
data = date.today()

print(item)
print(descricao)
print(data)

CPU
AMD Ryzen 5 5600GT
2026-06-04

In [103]:
new_data = pd.DataFrame([{
    'Item': item,
    'Descricao': descricao,
    'Preco': cpu_price,
    'Data': data
}])

df = pd.concat([df, new_data], ignore_index=True)
df

  Item           Descricao    Preco        Data
0  CPU  AMD Ryzen 5 5600GT  1032.93  2026-06-04

## Placa Mãe

In [104]:
driver.get('https://www.terabyteshop.com.br/produto/18646/placa-mae-msi-b550m-a-pro-chipset-b550-amd-am4-matx-ddr4?gad_source=1&gad_campaignid=16136003025&gclid=CjwKCAjw-dfOBhAjEiwAq0RwIz8B9H8t5nWpALxwlzeNSRzDe_0N0SyEK5sfVcw5-6LGCgzhKTTASBoCiYIQAvD_BwE')

In [ ]:
mboard_ptbr = driver.find_element(By.ID, 'valParc').get_property('innerText')
mboard_price = mboard_ptbr.split(' ')[1].replace(',', '.')
mboard_price = float(mboard)
mboard_price

647.05

In [106]:
item = 'Motherboard'
descricao = 'Chronos B550M-CR'
data = date.today()

print(item)
print(descricao)
print(data)

Motherboard
Chronos B550M-CR
2026-06-04

In [107]:
new_data = pd.DataFrame([{
    'Item': item,
    'Descricao': descricao,
    'Preco': mboard,
    'Data': data
}])

df = pd.concat([df, new_data], ignore_index=True)
df

          Item           Descricao    Preco        Data
0          CPU  AMD Ryzen 5 5600GT  1032.93  2026-06-04
1  Motherboard    Chronos B550M-CR   647.05  2026-06-04

## Memória RAM

In [108]:

driver.get('https://pt.aliexpress.com/item/1005008262724867.html?spm=a2g0o.productlist.main.5.3f49706cj2Wg2g&algo_pvid=5da52506-3ee1-492a-ab95-c239529a07de&algo_exp_id=5da52506-3ee1-492a-ab95-c239529a07de-4&pdp_ext_f=%7B"order"%3A"317"%2C"eval"%3A"1"%2C"fromPage"%3A"search"%7D&pdp_npi=6%40dis%21BRL%21159.51%21148.51%21%21%2129.31%2127.29%21%402103126e17792056972935357e4e6c%2112000044406707828%21sea%21BR%210%21ABX%211%210%21n_tag%3A-29910%3Bd%3Aeaf596e%3Bm03_new_user%3A-29895%3BpisId%3A5000000203576596&curPageLogUid=5imZUsCaxFjw&utparam-url=scene%3Asearch%7Cquery_from%3A%7Cx_object_id%3A1005008262724867%7C_p_origin_prod%3A')

In [109]:
button = driver.find_element(By.XPATH, "//div[contains(@title, '2PCS 8GB 3200')]")
button.click()

In [115]:
ram_price_ptbr = driver.find_element(By.XPATH, "/html/body/div[3]/div/div[1]/div/div[1]/div[1]/div[2]/div[4]/div/div[2]/div[1]/div[1]/span").get_property('innerText')
ram_price = ram_price_ptbr.split('$')[1].replace(',', '.')
ram_price = float(ram_price)
ram_price

548.21

In [116]:
item = 'RAM'
descricao = '2x Hyper X Fury DDR4 8GB 3200 MHz'
data = date.today()

print(item)
print(descricao)
print(data)

RAM
2x Hyper X Fury DDR4 8GB 3200 MHz
2026-06-04

In [117]:
new_data = pd.DataFrame([{
    'Item': item,
    'Descricao': descricao,
    'Preco': ram_price,
    'Data': data
}])

df = pd.concat([df, new_data], ignore_index=True)
df

          Item                          Descricao    Preco        Data
0          CPU                 AMD Ryzen 5 5600GT  1032.93  2026-06-04
1  Motherboard                   Chronos B550M-CR   647.05  2026-06-04
2          RAM  2x Hyper X Fury DDR4 8GB 3200 MHz   548.21  2026-06-04

## Gabinete

In [118]:
driver.get('https://www.kabum.com.br/produto/887046/gabinete-gaming-c3tech-aquarius-com-vidro-temperado-sem-fonte-mt-g860bk-')

In [119]:
gabinete_ptbr = driver.find_element(By.XPATH, "/html/body/div[1]/div/div[2]/div[1]/div[1]/div[1]/div[3]/div[2]/div[2]/span/b[1]").get_property('innerText')
gabinete_price = gabinete_ptbr.split('\xa0')[1].replace(',', '.')
gabinete_price = float(gabinete)
gabinete_price

299.83

In [120]:
item = 'Gabinete'
descricao = 'C3tech Aquarius'
data = date.today()

print(item)
print(descricao)
print(data)

Gabinete
C3tech Aquarius
2026-06-04

In [121]:
new_data = pd.DataFrame([{
    'Item': item,
    'Descricao': descricao,
    'Preco': gabinete_price,
    'Data': data
}])

df = pd.concat([df, new_data], ignore_index=True)
df

          Item                          Descricao    Preco        Data
0          CPU                 AMD Ryzen 5 5600GT  1032.93  2026-06-04
1  Motherboard                   Chronos B550M-CR   647.05  2026-06-04
2          RAM  2x Hyper X Fury DDR4 8GB 3200 MHz   548.21  2026-06-04
3     Gabinete                    C3tech Aquarius   299.83  2026-06-04

## Mouse

In [122]:
driver.get('https://pt.aliexpress.com/item/1005012249483667.html?spm=a2g0o.productlist.main.7.5327rUcurUcuiH&algo_pvid=e8050028-9dbc-49cf-acd4-b8139c3da673&algo_exp_id=e8050028-9dbc-49cf-acd4-b8139c3da673-6&pdp_ext_f=%7B"order"%3A"16"%2C"eval"%3A"1"%2C"fromPage"%3A"search"%7D&pdp_npi=6%40dis%21BRL%21161.11%21126.89%21%21%21199.15%21156.85%21%402101e80f17806035945658531e83f9%2112000057865859288%21sea%21BR%217714416806%21ABX%211%210%21n_tag%3A-29910%3Bd%3A137eff22%3Bm03_new_user%3A-29895%3BpisId%3A5000000207717525&curPageLogUid=gk4UPs5Mna8N&utparam-url=scene%3Asearch%7Cquery_from%3A%7Cx_object_id%3A1005012249483667%7C_p_origin_prod%3A')

In [124]:
button = driver.find_element(By.XPATH, '/html/body/div[3]/div/div[1]/div/div[1]/div[1]/div[2]/div[7]/div/div/div[2]/div/div/div/div/div[4]')
button.click()

In [125]:
mouse_ptbr = driver.find_element(By.XPATH, '/html/body/div[3]/div/div[1]/div/div[1]/div[1]/div[2]/div[3]/div/div[2]/div[1]/div[1]/span').get_property('innerText')
mouse_price = mouse_ptbr.split('$')[1].replace(',', '.')
mouse_price = float(mouse)
mouse_price

114.29

In [126]:
item = 'Mouse'
descricao = 'Attack Shark Wireless X11'
data = date.today()

print(item)
print(descricao)
print(data)

Mouse
Attack Shark Wireless X11
2026-06-04

In [127]:
new_data = pd.DataFrame([{
    'Item': item,
    'Descricao': descricao,
    'Preco': mouse_price,
    'Data': data
}])

df = pd.concat([df, new_data], ignore_index=True)
df

          Item                          Descricao    Preco        Data
0          CPU                 AMD Ryzen 5 5600GT  1032.93  2026-06-04
1  Motherboard                   Chronos B550M-CR   647.05  2026-06-04
2          RAM  2x Hyper X Fury DDR4 8GB 3200 MHz   548.21  2026-06-04
3     Gabinete                    C3tech Aquarius   299.83  2026-06-04
4        Mouse          Attack Shark Wireless X11   114.29  2026-06-04

## Headset

In [128]:
driver.get('https://pt.aliexpress.com/item/1005009495386384.html?aff_fcid=24cb7ac286da4a1dac72bd6b45a01629-1779218687223-01059-_c3gITj9D&tt=CPS_NORMAL&aff_fsk=_c3gITj9D&aff_platform=shareComponent-detail&sk=_c3gITj9D&aff_trace_key=24cb7ac286da4a1dac72bd6b45a01629-1779218687223-01059-_c3gITj9D&terminal_id=d874b61df0ea490bb40119dc36685fe8&afSmartRedirect=y')

In [129]:
button = driver.find_element(By.XPATH, '/html/body/div[3]/div/div[1]/div/div[1]/div[1]/div[2]/div[8]/div/div/div[2]/div/div/div/div/div[5]')
button.click()

In [130]:
headset_ptbr = driver.find_element(By.XPATH, '/html/body/div[3]/div/div[1]/div/div[1]/div[1]/div[2]/div[4]/div/div[2]/div[1]/div[1]/span').get_property('innerText')
headset_price = headset_ptbr.split('$')[1].replace(',', '.')
headset_price = float(headset)
headset_price

93.11

In [131]:
item = 'Headset'
descricao = 'BINNUNE Bluetooth'
data = date.today()

print(item)
print(descricao)
print(data)

Headset
BINNUNE Bluetooth
2026-06-04

In [132]:
new_data = pd.DataFrame([{
    'Item': item,
    'Descricao': descricao,
    'Preco': headset_price,
    'Data': data
}])

df = pd.concat([df, new_data], ignore_index=True)
df

          Item                          Descricao    Preco        Data
0          CPU                 AMD Ryzen 5 5600GT  1032.93  2026-06-04
1  Motherboard                   Chronos B550M-CR   647.05  2026-06-04
2          RAM  2x Hyper X Fury DDR4 8GB 3200 MHz   548.21  2026-06-04
3     Gabinete                    C3tech Aquarius   299.83  2026-06-04
4        Mouse          Attack Shark Wireless X11   114.29  2026-06-04
5      Headset                  BINNUNE Bluetooth    93.11  2026-06-04

## Soundbar

In [133]:
driver.get('https://pt.aliexpress.com/item/1005006436035998.html?spm=a2g0o.productlist.main.2.26c7y0DSy0DSur&algo_pvid=a6a82e3c-ebe8-41ee-9da0-1fe9c6c92b4a&algo_exp_id=a6a82e3c-ebe8-41ee-9da0-1fe9c6c92b4a-1&pdp_ext_f=%7B"order"%3A"4969"%2C"spu_best_type"%3A"price"%2C"eval"%3A"1"%2C"fromPage"%3A"search"%7D&pdp_npi=6%40dis%21BRL%21229.12%21100.55%21%21%21287.08%21125.98%21%402103212b17798072772552193e62f7%2112000037173402947%21sea%21BR%210%21ABX%211%210%21n_tag%3A-29910%3Bd%3Aeaf596e%3Bm03_new_user%3A-29895%3BpisId%3A5000000207258923&curPageLogUid=jr5V9vRJV1Bl&utparam-url=scene%3Asearch%7Cquery_from%3A%7Cx_object_id%3A1005006436035998%7C_p_origin_prod%3A')

In [135]:
soundbar_ptbr = driver.find_element(By.XPATH, '/html/body/div[3]/div/div[1]/div/div[1]/div[1]/div[2]/div[4]/div/div[2]/div[1]/div[1]/span').get_property('innerText')
soundbar_price = soundbar_ptbr.split('$')[1].replace(',', '.')
soundbar_price = float(soundbar)
soundbar_price

99.2

In [136]:
item = 'Soundbar'
descricao = 'NIYE V8'
data = date.today()

print(item)
print(descricao)
print(data)

Soundbar
NIYE V8
2026-06-04

In [137]:
new_data = pd.DataFrame([{
    'Item': item,
    'Descricao': descricao,
    'Preco': soundbar_price,
    'Data': data
}])

df = pd.concat([df, new_data], ignore_index=True)
df

          Item                          Descricao    Preco        Data
0          CPU                 AMD Ryzen 5 5600GT  1032.93  2026-06-04
1  Motherboard                   Chronos B550M-CR   647.05  2026-06-04
2          RAM  2x Hyper X Fury DDR4 8GB 3200 MHz   548.21  2026-06-04
3     Gabinete                    C3tech Aquarius   299.83  2026-06-04
4        Mouse          Attack Shark Wireless X11   114.29  2026-06-04
5      Headset                  BINNUNE Bluetooth    93.11  2026-06-04
6     Soundbar                            NIYE V8     99.2  2026-06-04

In [138]:
df.to_csv('PC_Gamer.csv', sep=';', index=None)