In [1]:
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import TimeoutException, NoSuchElementException
from datetime import date

In [2]:
df = pd.read_csv('../PC_Gamer.csv', sep=';')
df.tail(10)

                 Item                  Descricao    Preco        Data
82           Soundbar                    NIYE V8    97.78  2026-08-30
83  Soundbar Redragon           Redragon Adiemus   175.02  2026-08-30
84                CPU         AMD Ryzen 5 5600GT  1015.70  2026-09-06
85           Gabinete            C3tech Aquarius   289.70  2026-09-06
86            Teclado      M96 teclado bluetooth   196.17  2026-09-06
87              Mouse  Attack Shark Wireless X11   129.06  2026-09-06
88            Headset          BINNUNE Bluetooth   122.02  2026-09-06
89                SSD       Husky ssd nvme 512GB   829.50  2026-09-06
90           Soundbar                    NIYE V8    94.90  2026-09-06
91  Soundbar Redragon           Redragon Adiemus   168.01  2026-09-06

## LINKS

In [2]:
cpu_link = 'https://www.amazon.com.br/gp/aw/d/B0CQ4DTJYX?openid.assoc_handle=bramazon&openid.claimed_id=https%3A%2F%2Fwww.amazon.com.br%2Fap%2Fid%2Famzn1.account.AFSLCZAT6KPJPJL2MNOJJLJ4UUPA&openid.identity=https%3A%2F%2Fwww.amazon.com.br%2Fap%2Fid%2Famzn1.account.AFSLCZAT6KPJPJL2MNOJJLJ4UUPA&openid.mode=id_res&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.op_endpoint=https%3A%2F%2Fwww.amazon.com.br%2Fap%2Fsignin&openid.response_nonce=2026-08-01T19%3A18%3A36Z-7015999307553914865&openid.return_to=https%3A%2F%2Fwww.amazon.com.br%2Fgp%2Faw%2Fd%2FB0CQ4DTJYX&openid.signed=assoc_handle%2Cclaimed_id%2Cidentity%2Cmode%2Cns%2Cop_endpoint%2Cresponse_nonce%2Creturn_to%2Cns.pape%2Cpape.auth_policies%2Cpape.auth_time%2Csigned&openid.ns.pape=http%3A%2F%2Fspecs.openid.net%2Fextensions%2Fpape%2F1.0&openid.pape.auth_policies=http%3A%2F%2Fschemas.openid.net%2Fpape%2Fpolicies%2F2007%2F06%2Fnone&openid.pape.auth_time=2026-08-01T19%3A18%3A36Z&openid.sig=vZYwcxsW9yDyHL7oq%2FVX8u6giWcqbwWnMK7BYFzHluM%3D&serial='
motherboard_link = 'https://www.terabyteshop.com.br/produto/18646/placa-mae-msi-b550m-a-pro-chipset-b550-amd-am4-matx-ddr4?gad_source=1&gad_campaignid=16136003025&gclid=CjwKCAjw-dfOBhAjEiwAq0RwIz8B9H8t5nWpALxwlzeNSRzDe_0N0SyEK5sfVcw5-6LGCgzhKTTASBoCiYIQAvD_BwE'
motherboard_link_2 = 'https://pt.aliexpress.com/item/1005008817657298.html?spm=a2g0o.productlist.main.1.556aRSpFRSpFh2&algo_pvid=b8e2ca3c-15ad-4180-8feb-a61f99a893dd&algo_exp_id=b8e2ca3c-15ad-4180-8feb-a61f99a893dd-0&pdp_ext_f=%7B"order"%3A"2092"%2C"spu_best_type"%3A"price"%2C"eval"%3A"1"%2C"fromPage"%3A"search"%7D&pdp_npi=6%40dis%21BRL%211002.95%21413.77%21%21%211238.98%21511.14%21%402103138417857704306122904e1042%2112000047018663997%21sea%21BR%210%21ABX%211%210%21n_tag%3A-29910%3Bd%3A137eff22%3Bm03_new_user%3A-29895%3BpisId%3A5000000210893832&curPageLogUid=GilcjGxdhRys&utparam-url=scene%3Asearch%7Cquery_from%3A%7Cx_object_id%3A1005008817657298%7C_p_origin_prod%3A'
ssd_link = 'https://www.kabum.com.br/produto/626785/ssd-pcie-husky-thunderboost-512gb-m-2-nvme-leitura-2200mb-s-gravacao-1600mb-s-preto-hssd002512'
ram_link = 'https://pt.aliexpress.com/item/1005012323512000.html?pdp_ext_f=%7B"sku_id"%3A"12000058084377368"%7D&sourceType=1&spm=a2g0o.wish-manage-home.0.0&gatewayAdapt=glo2bra'
gabinete_link = 'https://www.kabum.com.br/produto/887046/gabinete-gaming-c3tech-aquarius-com-vidro-temperado-sem-fonte-mt-g860bk-'
mouse_link = 'https://pt.aliexpress.com/item/1005012371400759.html?spm=a2g0o.productlist.main.23.459c25f81bcfCL&algo_pvid=fe26c5bb-67a9-42a2-8835-77951b1c0678&algo_exp_id=fe26c5bb-67a9-42a2-8835-77951b1c0678-20&pdp_ext_f=%7B"order"%3A"23"%2C"eval"%3A"1"%2C"fromPage"%3A"search"%7D&pdp_npi=6%40dis%21BRL%21336.34%21147.99%21%21%21407.73%21179.40%21%402101f70717832764055654429e72c1%2112000058191763437%21sea%21BR%217714416806%21X%211%210%21n_tag%3A-29911%3Bd%3A137eff22%3Bm03_new_user%3A-29895&curPageLogUid=Lq0Biyq3hzZX&utparam-url=scene%3Asearch%7Cquery_from%3A%7Cx_object_id%3A1005012371400759%7C_p_origin_prod%3A'
headset_link = 'https://pt.aliexpress.com/item/1005009495386384.html?aff_fcid=24cb7ac286da4a1dac72bd6b45a01629-1779218687223-01059-_c3gITj9D&tt=CPS_NORMAL&aff_fsk=_c3gITj9D&aff_platform=shareComponent-detail&sk=_c3gITj9D&aff_trace_key=24cb7ac286da4a1dac72bd6b45a01629-1779218687223-01059-_c3gITj9D&terminal_id=d874b61df0ea490bb40119dc36685fe8&afSmartRedirect=y'
soundbar_link = 'https://pt.aliexpress.com/item/1005006436035998.html?spm=a2g0o.productlist.main.2.26c7y0DSy0DSur&algo_pvid=a6a82e3c-ebe8-41ee-9da0-1fe9c6c92b4a&algo_exp_id=a6a82e3c-ebe8-41ee-9da0-1fe9c6c92b4a-1&pdp_ext_f=%7B"order"%3A"4969"%2C"spu_best_type"%3A"price"%2C"eval"%3A"1"%2C"fromPage"%3A"search"%7D&pdp_npi=6%40dis%21BRL%21229.12%21100.55%21%21%21287.08%21125.98%21%402103212b17798072772552193e62f7%2112000037173402947%21sea%21BR%210%21ABX%211%210%21n_tag%3A-29910%3Bd%3Aeaf596e%3Bm03_new_user%3A-29895%3BpisId%3A5000000207258923&curPageLogUid=jr5V9vRJV1Bl&utparam-url=scene%3Asearch%7Cquery_from%3A%7Cx_object_id%3A1005006436035998%7C_p_origin_prod%3A'
keyboard_link = 'https://www.amazon.com.br/Teclado-Mecânico-Redragon-Kumara-Switch/dp/B0C1QFVYQJ/ref=asc_df_B0C1QFVYQJ?mcid=72fcea083724318fb0a2122c67ecec3d&tag=googleshopp00-20&linkCode=df0&hvadid=709884378379&hvpos=&hvnetw=g&hvrand=9615461458994901117&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=1001621&hvtargid=pla-2243950074900&psc=1&hvocijid=9615461458994901117-B0C1QFVYQJ-&hvexpln=0&language=pt_BR'
soundbar_red_link = 'https://pt.aliexpress.com/item/1005004684998034.html?spm=a2g0o.productlist.main.1.2c861240DubsIa&algo_pvid=f81d2e67-40df-4e0d-9058-324f7c10291f&algo_exp_id=f81d2e67-40df-4e0d-9058-324f7c10291f-0&pdp_ext_f=%7B"order"%3A"58"%2C"eval"%3A"1"%2C"fromPage"%3A"search"%7D&pdp_npi=6%40dis%21BRL%21380.93%21159.99%21%21%2168.05%2128.58%21%402101e7a317874373845623899e0f2e%2112000030094931478%21sea%21BR%217714416806%21X%211%210%21n_tag%3A-29911%3Bd%3A137eff22%3Bm03_new_user%3A-29895&curPageLogUid=08KMvNGPMgAU&utparam-url=scene%3Asearch%7Cquery_from%3A%7Cx_object_id%3A1005004684998034%7C_p_origin_prod%3A'

## Processador

In [15]:
driver = webdriver.Chrome()
driver.get(cpu_link)

driver.implicitly_wait(5)

try:
    # Tenta encontrar o elemento com o XPath específico
    botao_continuar = driver.find_element(By.XPATH, "/html/body/div/div[1]/div[3]/div/div/form/div/div/span")
    
    # Se encontrou, clica
    botao_continuar.click()
    print("Botão encontrado e clicado com sucesso!")
    
    # Aguarda a navegação após o clique
    WebDriverWait(driver, 5).until(EC.staleness_of(botao_continuar))
    
except NoSuchElementException:
    # Se não encontrou, apenas continua
    print("Botão NÃO encontrado. Continuando execução...")

Botão NÃO encontrado. Continuando execução...

In [20]:
best_offer = driver.find_element(By.XPATH, "//div[@class='a-section apex-core-price-identifier']/span[@class='a-price aok-align-center apex-pricetopay-value']").get_property('innerText')

price_cpu_ptbr = best_offer.split('\n')[0].split('R$')[1]
cpu_price = price_cpu_ptbr.replace('.', '').replace(',', '.')
cpu_price = float(cpu_price)
cpu_price

1033.53

In [8]:
item = 'CPU'
descricao = 'AMD Ryzen 5 5600GT'
data = date.today()

new_data = pd.DataFrame([{
    'Item': item,
    'Descricao': descricao,
    'Preco': cpu_price,
    'Data': data
}])

df = pd.concat([df, new_data], ignore_index=True)
df.tail(10)

           Item                       Descricao    Preco        Data
42     Soundbar                         NIYE V8    96.04  2026-07-05
43          CPU              AMD Ryzen 5 5600GT   995.08  2026-07-12
44  Motherboard                Chronos B550M-CR   647.05  2026-07-12
45          SSD          Movespeed ssd nvme 1TB   891.72  2026-07-12
46          RAM  1x JUHOR DDR4 8GB 3200MHz CL16   269.21  2026-07-12
47     Gabinete                 C3tech Aquarius   289.72  2026-07-12
48        Mouse       Attack Shark Wireless X11   140.23  2026-07-12
49      Headset               BINNUNE Bluetooth   112.12  2026-07-12
50     Soundbar                         NIYE V8    99.01  2026-07-12
51          CPU              AMD Ryzen 5 5600GT  1022.78  2026-07-17

## Motherboard

In [5]:
driver = webdriver.Chrome()
driver.get(motherboard_link)

In [10]:
mboard_ptbr = driver.find_element(By.ID, 'valParc').get_property('innerText')
mboard_price = mboard_ptbr.split(' ')[1].replace(',', '.')
mboard_price = float(mboard_price)
mboard_price

647.05

In [11]:
item = 'Motherboard'
descricao = 'Chronos B550M-CR'
data = date.today()

new_data = pd.DataFrame([{
    'Item': item,
    'Descricao': descricao,
    'Preco': mboard_price,
    'Data': data
}])

df = pd.concat([df, new_data], ignore_index=True)
df.tail(10)

           Item                       Descricao    Preco        Data
43          CPU              AMD Ryzen 5 5600GT   995.08  2026-07-12
44  Motherboard                Chronos B550M-CR   647.05  2026-07-12
45          SSD          Movespeed ssd nvme 1TB   891.72  2026-07-12
46          RAM  1x JUHOR DDR4 8GB 3200MHz CL16   269.21  2026-07-12
47     Gabinete                 C3tech Aquarius   289.72  2026-07-12
48        Mouse       Attack Shark Wireless X11   140.23  2026-07-12
49      Headset               BINNUNE Bluetooth   112.12  2026-07-12
50     Soundbar                         NIYE V8    99.01  2026-07-12
51          CPU              AMD Ryzen 5 5600GT  1022.78  2026-07-17
52  Motherboard                Chronos B550M-CR   647.05  2026-07-17

In [7]:
# MOTHERBOARD ALIEXPRESS
driver = webdriver.Chrome()
driver.get(motherboard_link_2)

In [8]:
button = driver.find_element(By.XPATH, "(//div[@class='action--stickyWrap--RtlPq66']/button)")
button.click()

## SSD

In [22]:
driver = webdriver.Chrome()
driver.get(ssd_link)

In [25]:
#button = driver.find_element(By.ID, "adopt-accept-all-button")
#button.click()

ssd_price_ptbr = driver.find_element(By.XPATH, "(//p[@class='text-xs font-normal leading-normal text-gray-700']/b[@class='text-xs'])").get_property('innerText')
ssd_price = ssd_price_ptbr.split('\xa0')[1].replace('.', '').replace(',', '.')
ssd_price = round(float(ssd_price)*10, 2)
ssd_price

829.5

In [21]:
item = 'SSD'
descricao = 'SSD Sandisk nvme 1TB'
data = date.today()

new_data = pd.DataFrame([{
    'Item': item,
    'Descricao': descricao,
    'Preco': ssd_price,
    'Data': data
}])

df = pd.concat([df, new_data], ignore_index=True)
df.tail(10)

           Item                       Descricao    Preco        Data
44  Motherboard                Chronos B550M-CR   647.05  2026-07-12
45          SSD          Movespeed ssd nvme 1TB   891.72  2026-07-12
46          RAM  1x JUHOR DDR4 8GB 3200MHz CL16   269.21  2026-07-12
47     Gabinete                 C3tech Aquarius   289.72  2026-07-12
48        Mouse       Attack Shark Wireless X11   140.23  2026-07-12
49      Headset               BINNUNE Bluetooth   112.12  2026-07-12
50     Soundbar                         NIYE V8    99.01  2026-07-12
51          CPU              AMD Ryzen 5 5600GT  1022.78  2026-07-17
52  Motherboard                Chronos B550M-CR   647.05  2026-07-17
53          SSD            SSD Sandisk nvme 1TB  1117.64  2026-07-17

## RAM

In [ ]:

driver.get(ram_link)

In [ ]:
#button = driver.find_element(By.XPATH, "//div[contains(@title, '2PCS 8GB 3200')]")
#button.click()

ram_price_ptbr = driver.find_element(By.XPATH, "//div[@class='price-default--currentWrap--A_MNgCG']").get_property('innerText')
ram_price = ram_price_ptbr.split('$')[1].replace(',', '.')
ram_price = float(ram_price)
ram_price

257.16

In [ ]:
item = 'RAM'
descricao = '1x JUHOR DDR4 8GB 3200MHz CL16'
data = date.today()

new_data = pd.DataFrame([{
    'Item': item,
    'Descricao': descricao,
    'Preco': ram_price,
    'Data': data
}])

df = pd.concat([df, new_data], ignore_index=True)
df.tail(10)

           Item                          Descricao    Preco        Data
21          CPU                 AMD Ryzen 5 5600GT  1031.76  2026-06-21
22  Motherboard                   Chronos B550M-CR   647.05  2026-06-21
23          RAM  2x Hyper X Fury DDR4 8GB 3200 MHz   581.99  2026-06-21
24     Gabinete                    C3tech Aquarius   299.83  2026-06-21
25        Mouse          Attack Shark Wireless X11   154.99  2026-06-21
26      Headset                  BINNUNE Bluetooth   105.61  2026-06-21
27     Soundbar                            NIYE V8   117.99  2026-06-21
28          CPU                 AMD Ryzen 5 5600GT  1000.15  2026-06-28
29  Motherboard                   Chronos B550M-CR   647.05  2026-06-28
30          RAM  2x Hyper X Fury DDR4 8GB 3200 MHz   526.99  2026-06-28

## Gabinete

In [7]:
driver = webdriver.Chrome()
driver.get(gabinete_link)

In [19]:
#button = driver.find_element(By.ID, "adopt-accept-all-button")
#button.click()

gabinete_ptbr = driver.find_element(By.XPATH, "(//p[@class='text-xs font-normal leading-normal text-gray-700']/b[@class='text-xs'])").get_property('innerText')
gabinete_price = gabinete_ptbr.split('\xa0')[1].replace(',', '.')
gabinete_price = round(float(gabinete_price)*10, 2)
gabinete_price

285.1

In [36]:
item = 'Gabinete'
descricao = 'C3tech Aquarius'
data = date.today()

new_data = pd.DataFrame([{
    'Item': item,
    'Descricao': descricao,
    'Preco': gabinete_price,
    'Data': data
}])

df = pd.concat([df, new_data], ignore_index=True)
df.tail(10)

           Item                          Descricao    Preco        Data
22  Motherboard                   Chronos B550M-CR   647.05  2026-06-21
23          RAM  2x Hyper X Fury DDR4 8GB 3200 MHz   581.99  2026-06-21
24     Gabinete                    C3tech Aquarius   299.83  2026-06-21
25        Mouse          Attack Shark Wireless X11   154.99  2026-06-21
26      Headset                  BINNUNE Bluetooth   105.61  2026-06-21
27     Soundbar                            NIYE V8   117.99  2026-06-21
28          CPU                 AMD Ryzen 5 5600GT  1000.15  2026-06-28
29  Motherboard                   Chronos B550M-CR   647.05  2026-06-28
30          RAM  2x Hyper X Fury DDR4 8GB 3200 MHz   526.99  2026-06-28
31     Gabinete                    C3tech Aquarius   289.72  2026-06-28

## Mouse

In [ ]:
driver.get(mouse_link)

In [15]:
#button = driver.find_element(By.XPATH, "(//div[@class='sku-item--image--jMUnnGA'])[3]")
#button.click()

mouse_ptbr = driver.find_element(By.XPATH, "(//div[@class='price-default--currentWrap--A_MNgCG'])").get_property('innerText')
mouse_price = mouse_ptbr.split('$')[1].replace(',', '.')
mouse_price = float(mouse_price)
mouse_price

127.97

In [42]:
item = 'Mouse'
descricao = 'Attack Shark Wireless X11'
data = date.today()

new_data = pd.DataFrame([{
    'Item': item,
    'Descricao': descricao,
    'Preco': mouse_price,
    'Data': data
}])

df = pd.concat([df, new_data], ignore_index=True)
df.tail(10)

           Item                          Descricao    Preco        Data
23          RAM  2x Hyper X Fury DDR4 8GB 3200 MHz   581.99  2026-06-21
24     Gabinete                    C3tech Aquarius   299.83  2026-06-21
25        Mouse          Attack Shark Wireless X11   154.99  2026-06-21
26      Headset                  BINNUNE Bluetooth   105.61  2026-06-21
27     Soundbar                            NIYE V8   117.99  2026-06-21
28          CPU                 AMD Ryzen 5 5600GT  1000.15  2026-06-28
29  Motherboard                   Chronos B550M-CR   647.05  2026-06-28
30          RAM  2x Hyper X Fury DDR4 8GB 3200 MHz   526.99  2026-06-28
31     Gabinete                    C3tech Aquarius   289.72  2026-06-28
32        Mouse          Attack Shark Wireless X11   136.13  2026-06-28

## Headset

In [ ]:
driver.get(headset_link)

In [ ]:
button = driver.find_element(By.XPATH, "//div[@data-sku-col='14-193']")
button.click()

headset_ptbr = driver.find_element(By.XPATH, "//div[@class='price-default--currentWrap--A_MNgCG']").get_property('innerText')
headset_price = headset_ptbr.split('$')[1].replace(',', '.')
headset_price = float(headset_price)
headset_price

In [45]:
item = 'Headset'
descricao = 'BINNUNE Bluetooth'
data = date.today()

new_data = pd.DataFrame([{
    'Item': item,
    'Descricao': descricao,
    'Preco': headset_price,
    'Data': data
}])

df = pd.concat([df, new_data], ignore_index=True)
df.tail(10)

           Item                          Descricao    Preco        Data
24     Gabinete                    C3tech Aquarius   299.83  2026-06-21
25        Mouse          Attack Shark Wireless X11   154.99  2026-06-21
26      Headset                  BINNUNE Bluetooth   105.61  2026-06-21
27     Soundbar                            NIYE V8   117.99  2026-06-21
28          CPU                 AMD Ryzen 5 5600GT  1000.15  2026-06-28
29  Motherboard                   Chronos B550M-CR   647.05  2026-06-28
30          RAM  2x Hyper X Fury DDR4 8GB 3200 MHz   526.99  2026-06-28
31     Gabinete                    C3tech Aquarius   289.72  2026-06-28
32        Mouse          Attack Shark Wireless X11   136.13  2026-06-28
33      Headset                  BINNUNE Bluetooth   120.81  2026-06-28

## Soundbar

In [26]:
driver = webdriver.Chrome()
driver.get(soundbar_link)

In [29]:
soundbar_ptbr = driver.find_element(By.XPATH, "(//span[@class='price-default--current--F8OlYIo'])").get_property('innerText')
soundbar_price = soundbar_ptbr.split('$')[1].replace(',', '.')
soundbar_price = float(soundbar_price)
soundbar_price

101.89

In [50]:
item = 'Soundbar'
descricao = 'NIYE V8'
data = date.today()

new_data = pd.DataFrame([{
    'Item': item,
    'Descricao': descricao,
    'Preco': soundbar_price,
    'Data': data
}])

df = pd.concat([df, new_data], ignore_index=True)
df.tail(10)

           Item                          Descricao    Preco        Data
25        Mouse          Attack Shark Wireless X11   154.99  2026-06-21
26      Headset                  BINNUNE Bluetooth   105.61  2026-06-21
27     Soundbar                            NIYE V8   117.99  2026-06-21
28          CPU                 AMD Ryzen 5 5600GT  1000.15  2026-06-28
29  Motherboard                   Chronos B550M-CR   647.05  2026-06-28
30          RAM  2x Hyper X Fury DDR4 8GB 3200 MHz   526.99  2026-06-28
31     Gabinete                    C3tech Aquarius   289.72  2026-06-28
32        Mouse          Attack Shark Wireless X11   136.13  2026-06-28
33      Headset                  BINNUNE Bluetooth   120.81  2026-06-28
34     Soundbar                            NIYE V8   104.11  2026-06-28

## SOUNDBAR REDRAGON

In [11]:
driver = webdriver.Chrome()
driver.get(soundbar_red_link)

driver.implicitly_wait(5)

try:
    # Tenta encontrar o elemento com o XPath específico
    button_close = driver.find_element(By.XPATH, "//div[@class='baxia-dialog-close']")
    
    # Se encontrou, clica
    button_close.click()
    print("Botão encontrado e clicado com sucesso!")
    
    # Aguarda a navegação após o clique
    #WebDriverWait(driver, 5).until(EC.staleness_of(button_close))
    
except NoSuchElementException:
    # Se não encontrou, apenas continua
    print("Botão NÃO encontrado. Continuando execução...")

Botão encontrado e clicado com sucesso!

In [4]:
button_close = driver.find_element(By.XPATH, "//div[@class='baxia-dialog-close']")
button_close.click()

In [9]:
soundbar_red_ptbr = driver.find_element(By.XPATH, "(//div[@class='price-default--currentWrap--A_MNgCG'])").get_property('innerText')
soundbar_red_price = soundbar_red_ptbr.split('$')[1].replace(',', '.')
soundbar_red_price = float(soundbar_red_price)
soundbar_red_price

149.76

In [ ]:
item = 'Soundbar Red'
descricao = 'Redragon Adiemus'
data = date.today()

new_data = pd.DataFrame([{
    'Item': item,
    'Descricao': descricao,
    'Preco': soundbar_red_price,
    'Data': data
}])

df = pd.concat([df, new_data], ignore_index=True)
df.tail(10)

## TECLADO

In [24]:
driver = webdriver.Chrome()
driver.get(keyboard_link)

In [7]:
button_close = driver.find_element(By.XPATH, "//div[@class='baxia-dialog-close']")
button_close.click()

In [8]:
button_option = driver.find_element(By.XPATH, "//div[@class='sku-item--showHot--hRxq3Vm sku-item--image--jMUnnGA']")
button_option.click()

In [ ]:
keyboard_ptbr = driver.find_element(By.XPATH, "//span[@class='best-offer-name a-text-bold']").get_property('innerText')

keyboard_price = keyboard_ptbr.split('\xa0')[1].split(' ')[0].replace(',', '.')
keyboard_price = float(keyboard_price)
keyboard_price

284.08

In [12]:
item = 'Teclado'
descricao = 'M96 teclado bluetooth'
data = date.today()

new_data = pd.DataFrame([{
    'Item': item,
    'Descricao': descricao,
    'Preco': keyboard_price,
    'Data': data
}])

df = pd.concat([df, new_data], ignore_index=True)
df.tail(10)

           Item                       Descricao   Preco        Data
74     Soundbar                         NIYE V8   93.01  2026-08-01
75          CPU              AMD Ryzen 5 5600GT  989.99  2026-08-10
76  Motherboard                Chronos B550M-CR  611.75  2026-08-10
77          SSD            Husky ssd nvme 512GB  794.30  2026-08-10
78          RAM  1x JUHOR DDR4 8GB 3200MHz CL16  252.79  2026-08-10
79     Gabinete                 C3tech Aquarius  289.70  2026-08-10
80        Mouse       Attack Shark Wireless X11  127.29  2026-08-10
81      Headset               BINNUNE Bluetooth  108.29  2026-08-10
82     Soundbar                         NIYE V8   95.77  2026-08-10
83      Teclado           M96 teclado bluetooth  189.07  2026-08-16

## Saving DataFrame

In [ ]:
df.to_csv('PC_Gamer_test.csv', sep=';', index=None)

driver.close()